[tool.ruff]
target-version = "py311"
line-length = 120
select = [
    "ALL",
]
ignore = [
    "D100", "D101", "D102", "D103", "D104", "D107",
    "RUF001", "RUF003",
    "PTH110", "PTH107",
    "CPY001",
    "TRY300", "TRY400",
    "ARG001", # Если есть декораторы, то он будет всегда ругаться, что нехорошо
    "LOG015", # Не понимаю, зачем нужен корневой, если я настраиваю нормально базовый
    "BLE001", # С течением времени, можно подлючить для более умных отлавливаний, но не сейчас
]

[tool.ruff.lint]
preview = true
